name: BuildBin

permissions:
  contents: write

on:
  push:

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Just
        uses: extractions/setup-just@v1

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
          components: clippy

      - name: Run linter
        run: just clippy
        env:
          RUST_BACKTRACE: 1
